apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::930050429294:user/viacheslav-user
      username: viacheslav-user
      groups:
        - system:masters
