apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  selector:
    project: training-eks-deployment
  ports:
    - name : training-eks-deployment-listener
      protocol : TCP
      port : 80
      targetPort: http-web
  type: LoadBalancer
